# for backwards compatibility

from Cython import __version__ as version

# For generated by string.

import time
watermark = "%s (Debian 0.20.1+git90-g0e6e38e-1ubuntu2) on %s" % (version, time.asctime())
